kind: pipeline
type: docker
name: CI/CD Pipeline

trigger:
  branch:
    - master
  event:
    - push
    - manual

steps:
  - name: test
    image: node:22
    pull: always
    commands:
      - apt-get update && apt-get install -y python3 python3-pip
      - pip3 install flake8 --break-system-packages
      - python3 -m flake8 --ignore=E501 sigma/

  - name: build-and-push
    image: plugins/docker
    depends_on:
      - test
    settings:
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_TOKEN
      repo: git.luciascipher.com/lucia/apex-sigma
      registry: git.luciascipher.com
      tags:
        - latest
    when:
      event: push
      branch: master

  - name: deploy
    image: alpine:latest
    depends_on:
      - build-and-push
    commands:
      - apk add --no-cache openssh-client
      - eval $(ssh-agent -s)
      - echo "$SSH_KEY" | ssh-add -
      - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /srv && docker-compose pull sigma_0 && docker-compose up -d sigma_0"
    when:
      event: push
      branch: master
